<br/>
<div class="container">
    <h1 class="text-center">Consulta de Usuários</h1>
    <hr>
    <form method="post" action="Request.php?class=UsuarioCtr&method=showList&page=1">
        <div class="form-row" > 
            <div class="form-group col-md-12">
                <label for="data[0]">Nome:</label>
                <input class="form-control" type="text" name="data[0]" value="<?= $this->sqlData[0] ?>">
            </div>    
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">                
                <label for="data[1]">Email:</label>
                <input type="text" class="form-control"  name="data[1]" id="email" value="<?= $this->sqlData[1] ?>">
            </div>  
            <div class="form-group col-md-6">                
                <label for="data[2]">Senha:</label>
                <input type="text" class="form-control"  name="data[2]" id="senha" value="<?= $this->sqlData[2] ?>">
            </div>           
        </div> 
        <div class="form-row" > 
            <div class="form-group col-md-4">
                <label for="data[3]">CPF:</label>
                <input type="text" class="form-control" id="inputCpf" name="data[3]"   value="<?= $this->sqlData[3] ?>">               
            </div>
            <div class="form-group col-md-4">
                <label for="data[4]">Telefone:</label>
                <input type="text" class="form-control" id="inputTelefone" name="data[4]" value="<?= $this->sqlData[4] ?>">
            </div>
            <div class="form-group col-md-4">
                <label for="page">Página:</label>
                <select name="limit" id="limit" class="custom-select">
                    <option <?= $this->regPerPage == 5 ? "selected" : '' ?> 
                        value="5">5</option>

                    <option <?= $this->regPerPage == 10 ? "selected" : '' ?> 
                        value="10">10</option>
                    <option <?= $this->regPerPage == 20 ? "selected" : '' ?> 
                        value="20">20</option>
                </select>   
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="text-center">  
                    <button  class="btn btn-primary" type="submit" name="command" value="OK">
                        Ok
                    </button>                       
                </div>
            </div>
        </div>
    </form>
</div>
<hr><hr>


<!--
<h1>Consulta de Usuários</h1>
<hr>
<form method="post" 
      action="Request.php?class=UsuarioCtr&method=showList&page=1">

    <label for="data[0]">Nome:</label>
    <input type="text" name="data[0]" value="<?= $this->sqlData[0] ?>">

    <label for="data[1]">CPF:</label>
    <input type="text" name="data[1]" value="<?= $this->sqlData[1] ?>">

    <label for="data[2]">Email:</label>
    <input type="text" name="data[2]" value="<?= $this->sqlData[2] ?>">

    <label for="data[3]">Telefone:</label>
    <input type="text" name="data[3]" value="<?= $this->sqlData[3] ?>">

    <label for="data[4]">Senha:</label>
    <input type="text" name="data[4]" value="<?= $this->sqlData[4] ?>">

    <br>
    <input type="submit" name="command" value="OK">
</form>

<br>

-->

<?php
$this->createList(
        $this->model, array('Nome', 'Cpf', 'Email', 'Telefone', 'Senha'), array('getNome', 'getCpf', 'getEmail', 'getTelefone', 'getSenha'), 'UsuarioCtr'
);
?>

