<footer class="footer-adm">
    <div class="container-fluid">
        <div class="container text-center">
            <span class="text-white">Thais Silveira &COPY; 2018</span>
        </div>
    </div>
</footer>
<script src="core/vendor/js/jquery-1.12.4.min.js"></script>
<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="core/vendor/js/owl.carousel.min.js"></script>
<!-- Imagesloaded JS -->
<script src="core/vendor/js/imagesloaded.pkgd.min.js"></script>
<!-- isotope JS -->
<!--<script src="core/vendor/js/jquery.isotope.v3.0.2.js"></script>-->
<!-- Smooth Scroll JS -->
<script src="core/vendor/js/smooth-scroll.min.js"></script>
<!-- venobox JS -->
<script src="core/vendor/js/venobox.min.js"></script>
<!-- ajaxchimp JS -->
<!--<script src="core/vendor/js/jquery.ajaxchimp.min.js"></script>-->
<!-- Slick Nav JS -->
<script src="core/vendor/js/jquery.slicknav.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.all.min.js"></script>
<script>
    $(document).ready(function () {

        $(window).on('load', function () {
            $('body').addClass('loaded');
        });
        /*=========================================================================
         Main Slider
         =========================================================================*/
        $('#main-slider').owlCarousel({
            loop: true,
            autoplay: true,
            smartSpeed: 500,
            items: 1,
            nav: true,
            navText: ['<i class="arrow_carrot-left"></i>', '<i class="arrow_carrot-right"></i>']
        });

        $("#main-slider").on("translate.owl.carousel", function () {
            $(".main_slide .slider_content h3").removeClass("animated fadeInUp").css("opacity", "0");
            $(".main_slide .slider_content h1").removeClass("animated fadeInUp").css("opacity", "0");
            $(".main_slide .slider_content p, .main_slide .slider_content .btn_group").removeClass("animated fadeInUp").css("opacity", "0");
        });

        $("#main-slider").on("translated.owl.carousel", function () {
            $(".main_slide .slider_content h3").addClass("animated fadeInUp").css("opacity", "1");
            $(".main_slide .slider_content h1").addClass("animated fadeInUp").css("opacity", "1");
            $(".main_slide .slider_content p, .main_slide .slider_content .btn_group").addClass("animated fadeInUp").css("opacity", "1");
        });

        // Página Cadastro Combos
        if ($(".cadastro-combos")[0]) {
            $.ajax({
                type: "GET",
                url: "Request.php",
                data: {
                    class: 'ComboCtr',
                    method: 'showJson',
<?php echo isset($_GET['id']) ? "id: '" . $_GET['id'] . "'" : '' ?>
                },
                dataType: 'json',
                success: function (data) {
                    // console.log(data);
                    if (!_.isEmpty(data.usuarios)) {
                        let usuarioHtml = '';
                        for (let usuario of data.usuarios) {
                            usuarioHtml += `<option value="${usuario.id}" ${usuario.selected}> ${usuario.nome}`;
                        }
                        $('#idUsuario').html(usuarioHtml);
                    }
                    if (!_.isEmpty(data.bebidas)) {
                        let bebidaHtml = '';
                        for (let bebida of data.bebidas) {
                            bebidaHtml += `<option value="${bebida.id}" ${bebida.selected}> ${bebida.descricao}`;
                        }
                        $('#idBebida').html(bebidaHtml);
                    }
                    if (!_.isEmpty(data.doces)) {
                        let doceHtml = '';
                        for (let doce of data.doces) {
                            doceHtml += `<option value="${doce.id}" ${doce.selected}> ${doce.descricao}`;
                        }
                        $('#idDoce').html(doceHtml);
                    }
                    if (!_.isEmpty(data.comidasalgadas)) {
                        let comidasalgadaHtml = '';
                        for (let comidasalgada of data.comidasalgadas) {
                            comidasalgadaHtml += `<option value="${comidasalgada.id}" ${comidasalgada.selected}> ${comidasalgada.descricao}`;
                        }
                        $('#idComidaSalgada').html(comidasalgadaHtml);
                    }
                }
            });
        }

        // Página Cadastro Usuário
        if ($(".cadastro-usuario")[0]) {
            var on_submit_function = function (e) {
                let campoEmail = $('#email').val();
                e.preventDefault();

                $.ajax({
                    type: "GET",
                    url: "Request.php",
                    data: {
                        class: 'UsuarioCtr',
                        method: 'checkEmail',
                        email: campoEmail
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data) {
                            $('#cadastroUsuario').off('submit', on_submit_function);
                            $('#commandSalvar').click();
                            return true;
                        } else {
                            Swal({
                                type: 'error',
                                html: 'E-mail já existente em nossa base de dados<br>Por favor, utilize outro e-mail.',
                                confirmButtonText: 'Entendi!'
                            });
                        }
                    }
                });
            };
            
            $('#cadastroUsuario').on('submit', on_submit_function);
        }
    });
</script>
</body>
</html>