<br/>
<div class="container">
    <h1 class="text-center">Consulta de Comida Salgada</h1>
    <hr>
    <form method="post" action="Request.php?class=ComidaSalgadaCtr&method=showList&page=1">
        <div class="form-row" > 
            <div class="form-group col-md-4">
                <label for="data[0]">Descrição:</label>
                <input class="form-control" type="text" name="data[0]" value="<?= $this->sqlData[0] ?>">
            </div>
            <div class="form-group col-md-4">                
                <label for="data[1]">Tipo:</label>
                <input type="text" class="form-control"  name="data[1]" value="<?= $this->sqlData[1] ?>">
            </div>
            <div class="form-group col-md-4">
                <label for="page">Página:</label>
                <select name="limit" id="limit" class="custom-select">
                    <option <?= $this->regPerPage == 5 ? "selected" : '' ?> 
                        value="5">5</option>

                    <option <?= $this->regPerPage == 10 ? "selected" : '' ?> 
                        value="10">10</option>
                    <option <?= $this->regPerPage == 20 ? "selected" : '' ?> 
                        value="20">20</option>
                </select>   
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="text-center">  
                    <button  class="btn btn-primary" type="submit" name="command" value="OK">
                        Ok
                    </button>                       
                </div>
            </div>
        </div>
    </form>
</div>
<hr><hr>

<!--<h2>Consulta de Comida</h2>
<hr>

<form method="post" action="Request.php?class=ComidaSalgadaCtr&method=showList&page=1">

    <label for="descricao">Descrição:</label>
    <input type="text" name="data[0]" id="descricao"
           value="<?= $this->sqlData[0] ?>">
    <br>

    <label for="tipo">Tipo:</label>
    <input type="text" name="data[1]" id="tipo"
           value="<?= $this->sqlData[1] ?>">
    <br>
    <label for="limit">Registros por página</label>

    <select name="limit" id="limit">
        <option <?= $this->regPerPage == 5 ? "selected" : '' ?> 
            value="5">5</option>

        <option <?= $this->regPerPage == 10 ? "selected" : '' ?> 
            value="10">10</option>
        <option <?= $this->regPerPage == 20 ? "selected" : '' ?> 
            value="20">20</option>
    </select>    

    <input type="submit" name="command" value="OK">
</form>

-->
<?php
//var_dump($_POST);
$this->createList($this->model, array('Descricao', 'Tipo'), array('getDescricaoComida', 'getTipoComida'), 'ComidaSalgadaCtr');
?>